### ISSUE TITLE
Energy and Progress Bar Disappearing

### ISSUE THREAD

**Issue by Elliott-Smith** [McJty/YouTubeModdingTutorial#1]
If you double click on any slot in the furnace the progress bar and energy bar disappear if neither of them get updated by the server. If an update occurs they reappear. If the furnace is being updated and you double click you can see the GUI elements flicker.

**Comment by McJty** [comment]
That's an interesting bug. I'll spend next episode on figuring that out

**Comment by McJty** [comment]
I have figured out what's wrong and will show the fix next episode

**Comment by Elliott-Smith** [comment]
Awesome, looking forward to see what was wrong

**Comment by strikerrocker** [comment]
Can be closed?

**Comment by McJty** [comment]
yep
